### ISSUE TITLE
Could we add a collector for getting usage of /var/lib/prometheus/metrics ?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/supportutils-plugin-ses#11]
We had to realize that /var/lib/prometheus/metrics causes /var running out of available disk space and due to that we need planing information and usage at existing deployments.

Maybe a find on this directory or a sub-dir ls with all details?
And also a du -sh or similar would be great.

**Comment by denisok** [comment]
@Martin-Weiss https://github.com/SUSE/supportutils-plugin-ses/pull/12 please review it.

**Comment by tserong** [comment]
Done in #12
