### ISSUE TITLE
does it make sense to include prometheus and grafana statuses to ses support plugin?

### ISSUE THREAD

**Issue by denisok** [SUSE/supportutils-plugin-ses#7]
@jan--f @tserong in our internal bug 1098853, I looked into the ses plugin logs to check what are the status of the services, but looks like there no such thing.
Is it easy to see somewhere in the logs, or it make sense to add "systemctl status -l" for those services?

BTW are we gathering configs for those in the suportconfig?

**Comment by tserong** [comment]
If anything horribly bad has happened (to any service) it should be visible in messages.txt, which is grabbed by supportconfig itself, not by the ses plugin. There's also systemd.txt, which gives some information about running/loaded/configured services, but not actual `systemctl status` output.

I *do* think we should add something to get more information about prometheus and grafana, but possibly we should do this in the base supportconfig, on the assumption it's not just SES using these tools.

**Comment by denisok** [comment]
`systemctl status -l` shows not only process status which is in systemd.txt but also latest log info, like why it fails.

But yes, info could be parsed from other files.

**Comment by jan--f** [comment]
I'll look into this.

**Comment by tserong** [comment]
Fixed by 7f7d8be (via #10).
